### ISSUE TITLE
Configure container div styles

### ISSUE THREAD

**Issue by KamalAman** [godspeed20/mui-editable-table#5]
It would be very helpful if I could pass in styles into  MuiEditableTable which then styles the parent container.

Right now the parent container only gets 

```
 <div className="container">
```

should become 

```
 <div className="container" style={this.props.style}>
```

And the definition would like so:

```
<MuiEditableTable
    colSpec={this.props.tagProperties}
    style={{
      maxWidth: "500px"
    }}
    rowData={this.state.tags || []}
    onChange={(rows) => {
      this.setState({
        tags: rows
      });
   }}
  />
```

**Comment by godspeed20** [comment]
Have added what you've suggested and pushed to npm, see if that covers what you're after. thanks for the suggestion

**Comment by godspeed20** [comment]
Going to close this now as i haven't heard anything further. let me know if it doesn't quite fit what you were expecting
