### ISSUE TITLE
Multiple copies of React

### ISSUE THREAD

**Issue by therealbenjamin** [godspeed20/mui-editable-table#6]
I am new to React and experimenting with this package, and keep encountering this error:

`Uncaught Error: Element ref was specified as a string (mui-editable-table-count) but no owner was set. You may have multiple copies of React loaded.`

I am importing `MuiEditableTable`, then setting `this.state.familyContacts` as an array of objects in `componentDidMount`, and rendering:

    render() {
        const colSpec = [
            { title: 'Name', fieldName: 'name', inputType: "TextField", width: 200 },
            { title: 'Phone', fieldName: 'phone', inputType: "TextField", width: 200 },
            { title: 'Relationship', fieldName: 'relationship', inputType: "TextField", width: 200 },
            { title: 'Active', fieldName: 'active', inputType: "Toggle", width: 200 }
        ];

        return (
            <MuiEditableTable
                colSpec={colSpec}
                rowData={this.state.familyContacts}
                onChange={this.onChange}
            />
        );
    }

Any idea why this might lead to the error in `mui-editable-table-count`?

**Comment by therealbenjamin** [comment]
Closing - I had unmet dependencies.

**Comment by yunesco** [comment]
Hey , @therealbenjamin  Whats was the issue? i am having the same problem
